name: approval_online
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.13.2
  get_storage: ^1.3.1
  percent_indicator: ^2.1.3

flutter:
  uses-material-design: true
